# Computer tools in education

We are going to discuss Math software: Octave, SageMath, GeoGebra, LaTeX.

* Octave — software for numerical evaluation, a free analog of MatLab, etc.
* SageMath — software for symbolic manipulations, a free analog of Mathemaica, Maple, etc. For example, `expand((x - 1)*(x + 2))` is computed to `x^2 + x - 2`.
* GeoGebra — school geometry, make geometrical constructions, observe gemetrical facts, etc. For example, you may construct a triangle, then construct medians and see that they really intersect in one point. If you move vertices, you see that medians still intersect.
* LaTeX — typesettings system, a kind of Microsoft Word, but it is easier in LaTeX to write formulas.

## Octave

A software to make numeric computations. Feature-Comparable with matlab. If some code works for Matlab, Octave tries to run this code also.
One of the reasons to study octave. Its main object it works are matrices. (MatLab = matrix laboratory). Numpy, for example, is based on ideas from Octave. So, if you study octave, you also study numpy. Numpy is a numeric computations library for Python.

Octave (Matlab) has a programming language, designed for mathematitians.

### how to use octave

You can install it, and you will have Octave by itself and a Graphical User Interface (GUI) for it

You can use octave online. octave-online.com (only if you are not able to install)

# The Octave (MatLab) language
## How to create matrices

If you write a number, this is a 1x1 matrix with that number

In [3]:
2

ans = 2


If you want to have a bigger matrix, write it in `[` and `]`. Split numbers by space or a comma, split lines by a semicolon or a newline:

In [6]:
[1 2 3 ; 4 5 6]
[1, 2, 3; 4, 5, 6]
[1 2 3
 4 5 6]

ans =

   1   2   3
   4   5   6



ans =

   1   2   3
   4   5   6



ans =

   1   2   3
   4   5   6



you can create variables and assign matrices to them:

In [7]:
a = [1 2 3; 4 5 6]
b = [3 4; 5 6; 9 10]

a =

   1   2   3
   4   5   6



b =

    3    4
    5    6
    9   10



we can combine matrices:

In [12]:
a = [1 2; 3 4]
[a a]
[a ; a]
[a a a; 10 20 30 40 50 60]
% [a a a; 10 20] - an error

a =

   1   2
   3   4



ans =

   1   2   1   2
   3   4   3   4



ans =

   1   2
   3   4
   1   2
   3   4



ans =

    1    2    1    2    1    2
    3    4    3    4    3    4
   10   20   30   40   50   60



### The range operator
A colon creates a matrix:

In [17]:
1:10
10:20
10:3:20  % use step 3
0:0.1:1  % 11 numbers: 0 0.1 0.2 0.3     1
0:(1/9):1        % 10 numbers from 0 to 1, the step should be 1/9

ans =

    1    2    3    4    5    6    7    8    9   10



ans =

   10   11   12   13   14   15   16   17   18   19   20



ans =

   10   13   16   19



ans =

 Columns 1 through 8:

         0    0.1000    0.2000    0.3000    0.4000    0.5000    0.6000    0.7000

 Columns 9 through 11:

    0.8000    0.9000    1.0000



ans =

 Columns 1 through 8:

         0    0.1111    0.2222    0.3333    0.4444    0.5556    0.6667    0.7778

 Columns 9 and 10:

    0.8889    1.0000



In [18]:
[1:10 ; 2:11]

ans =

    1    2    3    4    5    6    7    8    9   10
    2    3    4    5    6    7    8    9   10   11



### Functions to create matrices
similar to `:`, but you say not the step, you say number of elements:

In [19]:
linspace(0, 1, 10)  % 10 numbers from 0 to 1

ans =

 Columns 1 through 8:

        0   0.1111   0.2222   0.3333   0.4444   0.5556   0.6667   0.7778

 Columns 9 and 10:

   0.8889   1.0000



In [20]:
linspace(0, 1, 11)

ans =

 Columns 1 through 8:

        0   0.1000   0.2000   0.3000   0.4000   0.5000   0.6000   0.7000

 Columns 9 through 11:

   0.8000   0.9000   1.0000



A matrix of zeroes, ones, diagonal matrix:

In [21]:
zeros(5)  %5x5
zeros(2, 4) % 2x4
ones(4)  % 4x4
ones(10, 1)  % 10x1

ans =

   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0



ans =

   0   0   0   0
   0   0   0   0



ans =

   1   1   1   1
   1   1   1   1
   1   1   1   1
   1   1   1   1



ans =

   1
   1
   1
   1
   1
   1
   1
   1
   1
   1



In [24]:
eye(5) % 5x5 with 1s on diag
eye(3, 5)  % 3x5 with 1s on diag

ans =

Diagonal Matrix

   1   0   0   0   0
   0   1   0   0   0
   0   0   1   0   0
   0   0   0   1   0
   0   0   0   0   1



ans =

Diagonal Matrix

   1   0   0   0   0
   0   1   0   0   0
   0   0   1   0   0



In [26]:
diag([1 2 3]) % provide a row of numbers, creates a diagonal matrix with this number
diag(1:10)

ans =

Diagonal Matrix

   1   0   0
   0   2   0
   0   0   3



ans =

Diagonal Matrix

    1    0    0    0    0    0    0    0    0    0
    0    2    0    0    0    0    0    0    0    0
    0    0    3    0    0    0    0    0    0    0
    0    0    0    4    0    0    0    0    0    0
    0    0    0    0    5    0    0    0    0    0
    0    0    0    0    0    6    0    0    0    0
    0    0    0    0    0    0    7    0    0    0
    0    0    0    0    0    0    0    8    0    0
    0    0    0    0    0    0    0    0    9    0
    0    0    0    0    0    0    0    0    0   10

