# Creating matrices

## Specify elements

Use square brackets to compose a matrix from smaller elements. A __space__ or a __comma__ means putting in the same line. A __new line__ or a __semicolon__ means putting on the next line.

All the following examples create the same matrix

In [2]:
a = [1 2; 3 4]
b = [1, 2; 3, 4]
c = [1, 2
     3  4]

a =

   1   2
   3   4

b =

   1   2
   3   4

c =

   1   2
   3   4



Here are examples of row and column matrices:

In [4]:
a = [1 2 3 4 10 20]
b = [10; 20; 30]

a =

    1    2    3    4   10   20

b =

   10
   20
   30



You can compose matrices of smaller ones:

In [12]:
a = [1 2; 3 4]
b = [0 0]
c = [a; b] # put a on top of b
d = [a a; b b] # put a next to a, and in the next line put b next to b
e = [a; 5 6] # add a row below a

a =

   1   2
   3   4

b =

   0   0

c =

   1   2
   3   4
   0   0

d =

   1   2   1   2
   3   4   3   4
   0   0   0   0

e =

   1   2
   3   4
   5   6



## Range operator

Use the colon operator to create a row matrix consisting of consecutive numbers: 

In [16]:
a = 1:10 # numbers from 1 to 10
b = 1:2:10 # numbers from 1 to 10 with step 2
c = 10:-1:1 # numbers from 10 downto 1
d = 1:0.1:2 # numbers from 1 to 2 with the step 0.1

a =

    1    2    3    4    5    6    7    8    9   10

b =

   1   3   5   7   9

c =

   10    9    8    7    6    5    4    3    2    1

d =

 Columns 1 through 8:

    1.0000    1.1000    1.2000    1.3000    1.4000    1.5000    1.6000    1.7000

 Columns 9 through 11:

    1.8000    1.9000    2.0000



## Functions that create matrices

`linspace` is similar to the range operators, but allows for specifying the number of points instead of the step size:

In [24]:
a = linspace(1, 2, 21) # Creates numbers from 1 to 2 in such
                       # a way that there are exactly 21 numbers.
b = 1:1/20:2 # you get the same result with the range operator

a =

 Columns 1 through 8:

   1.0000   1.0500   1.1000   1.1500   1.2000   1.2500   1.3000   1.3500

 Columns 9 through 16:

   1.4000   1.4500   1.5000   1.5500   1.6000   1.6500   1.7000   1.7500

 Columns 17 through 21:

   1.8000   1.8500   1.9000   1.9500   2.0000

b =

 Columns 1 through 8:

    1.0000    1.0500    1.1000    1.1500    1.2000    1.2500    1.3000    1.3500

 Columns 9 through 16:

    1.4000    1.4500    1.5000    1.5500    1.6000    1.6500    1.7000    1.7500

 Columns 17 through 21:

    1.8000    1.8500    1.9000    1.9500    2.0000



In [30]:
a = zeros(2, 3) # matrix consisting of zeros, of the 2x3 size
b = ones(3, 2) # matrix consisting of ones, of the 2x3 size
c = eye(4, 6) # matrix consisting of zeros, but with ones on the main diagonal
d = zeros(3) # one argument (for any of the previous functions) creates a square matrix of the specified size

a =

   0   0   0
   0   0   0

b =

   1   1
   1   1
   1   1

c =

Diagonal Matrix

   1   0   0   0   0   0
   0   1   0   0   0   0
   0   0   1   0   0   0
   0   0   0   1   0   0

d =

   0   0   0
   0   0   0
   0   0   0

