# Индексирование

Индексирование позволяет обратиться к отдельным элементам матрицы или выделить подматрицу. Мы будем использовать следующие три матрицы в примерах дальше.

In [1]:
a = 10 * ((1:5) + (0:5:20)')
b = 10 * (1:6)
c = 10 * (1:6)'

a =

    10    20    30    40    50
    60    70    80    90   100
   110   120   130   140   150
   160   170   180   190   200
   210   220   230   240   250

b =

   10   20   30   40   50   60

c =

   10
   20
   30
   40
   50
   60



In [2]:
a(2, 3) # элемент из второй строки, третьего столбца
a(5, 5) # элемент из пятой строки, пятого столбца
a(2, 3) = 81 # можно перезаписать значение элемента в матрице
b(3) # матрицы b и c одномерные, с ними можно пользоваться одним индексом
c(4)
c(4, 1) # но можем и два: четвертая строка, первый столбец

ans =  80
ans =  250
a =

    10    20    30    40    50
    60    70    81    90   100
   110   120   130   140   150
   160   170   180   190   200
   210   220   230   240   250

ans =  30
ans =  40
ans =  40


Хотя матрица $a$ и двумерная, с ней все равно можно использовать один индекс для доступа. Элементы отсчитываются с левого верхнего элемента вниз по столбцам.

In [3]:
a(3)
a(8)
a(8) = 122

ans =  110
ans =  120
a =

    10    20    30    40    50
    60    70    81    90   100
   110   122   130   140   150
   160   170   180   190   200
   210   220   230   240   250



## Подматрицы

Индексы могут быть не только числами, но и матрицами. Если указывать два индекса, то первая матрица перечисляет номера строк, вторая - столбцов.

In [4]:
row = 3;
col = 4;
a(row, col) # это обычный способ индексирования, номер строки и столбца
rows = [3, 4];
cols = [3, 4, 5];
a(rows, cols) # выбор подматрицы из указанных строк и столбцов
a([3, 4, 3], [1, 2]) # одну и ту же строку или столбец можно выбирать несколько раз 

ans =  140
ans =

   130   140   150
   180   190   200

ans =

   110   122
   160   170
   110   122



In [5]:
Очень часто необходимо выбртаь строку или столбец целиком:

parse error:

  invalid character '' (ASCII 208)

>>> Очень часто необходимо выбртаь строку или столбец целиком:
    ^



In [6]:
a(1, [1, 2, 3, 4, 5]) # Здесь выбрана вся первая строка, потому что указаны все столбцы 
a(1, 1:5) # Аналогичный результат можно получить оператором диапазона.
          # 1:5 равно [1 2 3 4 5]
a(1, 1:end) # ключевое слово `end` всегда означает "индекс последнего элемента"
a(1, 1:end-1) # можно делать вычисления с `end`, например, взять всё кроме последнего
              # элемента
a(1, (end+1)/2:end) # можно взять вторую половину строки
a(1, :) # для случая `1:end` есть специальное сокращение `:`.

ans =

   10   20   30   40   50

ans =

   10   20   30   40   50

ans =

   10   20   30   40   50

ans =

   10   20   30   40

ans =

   30   40   50

ans =

   10   20   30   40   50



Синтаксис с индексом в виде двоеточия используется очень часто:

In [7]:
a(2, :) # вторая строка
a(:, 3) # третий столбец
a(:, :) # выбрать всё (не очень полезно, потому что это почти всегда аналогично `a`)

ans =

    60    70    81    90   100

ans =

    30
    81
   130
   180
   230

ans =

    10    20    30    40    50
    60    70    81    90   100
   110   122   130   140   150
   160   170   180   190   200
   210   220   230   240   250



Подматрицам, полученным с помощью индексирования, можно присваивать значения.

In [8]:
a([1, 2], [3, 4]) # подматрица 2 на 2
a([1, 2], [3, 4]) = [31 41; 82 91] # присваиваем матрицу того же размера
a(4:5, 4:5) # опять подматрица 2 на 2
a(4:5, 4:5) = 200 # можно присвоить одно число, в этом случае оно копируются
                  # во все клетки
aa = a # сделаем копию матрицы, чтобы не испортить ее следующей строкой: 
aa(:, :) = 1 # скопировать 1 во все элементы матрицы. Трудно придумать ситуацию,
             # кодга это нужно, но такая возможность есть.

ans =

   30   40
   81   90

a =

    10    20    31    41    50
    60    70    82    91   100
   110   122   130   140   150
   160   170   180   190   200
   210   220   230   240   250

ans =

   190   200
   240   250

a =

    10    20    31    41    50
    60    70    82    91   100
   110   122   130   140   150
   160   170   180   200   200
   210   220   230   200   200

aa =

    10    20    31    41    50
    60    70    82    91   100
   110   122   130   140   150
   160   170   180   200   200
   210   220   230   200   200

aa =

   1   1   1   1   1
   1   1   1   1   1
   1   1   1   1   1
   1   1   1   1   1
   1   1   1   1   1



## Другие возможности
Следующий хитрый пример напоминает, что происходит, когда к двумерной матрице обращаются по одному индексу. Один индекс означает, что элементы считаются по столбцам, начиная с левого верхнего элемента. Поэтому двумерную матрицу можно превратить в одномерную следующим образом:

In [9]:
a(:)

ans =

    10
    60
   110
   160
   210
    20
    70
   122
   170
   220
    31
    82
   130
   180
   230
    41
    91
   140
   200
   200
    50
   100
   150
   200
   200



Рассмотрим такой пример:

In [10]:
a = [10 20]
i = [1 1 2; 2 1 2; 2 2 1]
a(i)

a =

   10   20

i =

   1   1   2
   2   1   2
   2   2   1

ans =

   10   10   20
   20   10   20
   20   20   10



Если при индексировании в качестве индекса используется матрица, то в результате создается матрица того же размера, что и матрица индексов. В ней в каждой клетке пишется элемент исходной матрицы с соответствующим индексом.

Это иногда используют, чтобы создать матрицу из одинаковых значений:

In [11]:
42(ones(2, 3))

ans =

   42   42   42
   42   42   42

