# Матричные операции
## Арифметические поэлементные операции
Начнем с арифметических операций. Предположим, что мы имеет две матрицы размера $2\times3$:

In [1]:
a = [10 10 10; 20 20 20]
b = [1 2 3; 4 5 6]

a =

   10   10   10
   20   20   20

b =

   1   2   3
   4   5   6



Следующие операции работают поэлементо. Это значит, что они при применении к матрицам одинакового размера, создают матрицу такого же размера, где каждый элемент в строке $i$, столбце $j$ получается как результат операции над элементом строки $i$ столбца $j$ первой матрицы, и элементом строки $i$ столбца $j$ второй матрицы матрицы:
* сложить `+` (аналогично `.+`)
* вычесть (аналогично `.-`)
* умножить `.*`
* поделить `./`
* левое деление `.\`
* в степень`.^` (аналогично `.**`)

In [2]:
a_add_b = a + b  # символ _ всего лишь является частью имени переменной
a_sub_b = a - b
a_mul_b = a .* b
a_div_b = a ./ b
b_div_a = a .\ b  # аналогично b ./ a
a_pow_b = a .^ b

a_add_b =

   11   12   13
   24   25   26

a_sub_b =

    9    8    7
   16   15   14

a_mul_b =

    10    20    30
    80   100   120

a_div_b =

   10.0000    5.0000    3.3333
    5.0000    4.0000    3.3333

b_div_a =

   0.10000   0.20000   0.30000
   0.20000   0.25000   0.30000

a_pow_b =

         10        100       1000
     160000    3200000   64000000



In [3]:
eye(3) + ones(3)  # в этом примере добавляем единичную матрицу к матрице из единиц

ans =

   2   1   1
   1   2   1
   1   1   2



Эти операции, конечно, работают и с числами, потому что в octave числа можно воспринимать как матрицы размера $1\times1$:

In [4]:
2 + 2

ans =  4


Все рассмотренные операции можно применять и для матриц разного размера, что при этом происходит, будет подробно разобрано в разделе об автосогласовании размеров операндов (broadcasting).

## Матричные арифметические операции
### Умножение матриц
Следущие операции считают свои аргументы матрицами, и выполняют действия в матричной алгебре. В этом случае умножение матриц определяется как в алгебре, и принципиально отличается от поэлементного умножения из предыдущего раздела. Введем несколько матриц и перемножим их:

In [5]:
id = [1 0 0; 0 1 0; 0 0 1] # an identity matrix, the same as eye(3)
a = [1 2 3; 3 2 1; -1 -2 -3]
b = [1 -1; 2 -2; 0 1]
c = [1 1 2] # матрица-строка
d = [1; 1; 2] # матрица-столбец
id_mul_a = id * a  # умножение на id не изменяет матрицу
id_mul_b = id * b  # аналогично, получается опять b
a_mul_b = a * b
b * a # это перемножение невозможно, потому что размеры b и a не согласются. 
c_mul_d = c * d # при умножении строки на столбец получается число: 1*1 + 1*1 + 2 * 2 = 6
d_mul_c = d * c # при умножении столбца на строку, получается матрица из всех возможных
                # произведений пар

id =

   1   0   0
   0   1   0
   0   0   1

a =

   1   2   3
   3   2   1
  -1  -2  -3

b =

   1  -1
   2  -2
   0   1

c =

   1   1   2

d =

   1
   1
   2

id_mul_a =

   1   2   3
   3   2   1
  -1  -2  -3

id_mul_b =

   1  -1
   2  -2
   0   1

a_mul_b =

   5  -2
   7  -6
  -5   2

error: operator *: nonconformant arguments (op1 is 3x2, op2 is 3x3)
c_mul_d =  6
d_mul_c =

   1   1   2
   1   1   2
   2   2   4



Еще один пример, что операции `*` и `.*` значительно отличаются:

In [6]:
[1 2 3] .* [1 2 3] # работает
[1 2 3] * [1 2 3] # ошибка из-за несоответствия размеров матриц

ans =

   1   4   9

error: operator *: nonconformant arguments (op1 is 1x3, op2 is 1x3)


### Деление матриц
*этот раздел можно пропустить при первом прочтении*

Операция деления обратна к умножению. Если `A = B * C`, то `B = A / C` и `C = B \ A`.
Эти операции определены так, что `(X / Y) * Y = X` и `X * (X \ Y) = Y`.

Операции также можно определить как `X / Y = X * inv(Y)` и `X \ Y = inv(X) * Y`, где `inv(X)` это обратная к матрице `X`. Но это определение работает только в случаях, когда `X` квадратна, и у нее существует обратная.

In [7]:
a = [1 2; 3 4]
b = [1 2; 1 3]
a_mul_b = a * b
should_be_a = a_mul_b / b
should_be_b = a \ a_mul_b

a =

   1   2
   3   4

b =

   1   2
   1   3

a_mul_b =

    3    8
    7   18

should_be_a =

   1   2
   3   4

should_be_b =

   1.00000   2.00000
   1.00000   3.00000



Деление работает и для неквадратных матриц: 

In [8]:
a = [1 2; 3 4; 5 6]
b = [2; 3]
a_mul_b = a * b # давайте умножим две матрицы разного размера
not_exactly_a = a_mul_b / b # результат отличается от a, но ...
the_same_as_a_mul_b = not_exactly_a * b # но при проверке умножением опять
                                        # получается исходный результат

a =

   1   2
   3   4
   5   6

b =

   2
   3

a_mul_b =

    8
   18
   28

not_exactly_a =

   1.2308   1.8462
   2.7692   4.1538
   4.3077   6.4615

the_same_as_a_mul_b =

    8.0000
   18.0000
   28.0000



### Матричная степень

Операция возведения в степень работает только для чисел и квадратных матриц:

In [9]:
2 ^ 3 # аналогично 2 ** 3
pow3 = [1 1; 0 1] ^ 3 # возведение в третью степень, аналогично следующему:
pow3 = [1 1; 0 1] * [1 1; 0 1] * [1 1; 0 1]

2 ^ [1 2; 3 4] # возведение в матричную степень, это продвинутая операция, которая не понадобится в курсе
2 .^ [1 2; 3 4] # а вот возведение в степень поэлементно вполне может пригодиться

ans =  8
pow3 =

   1   3
   0   1

pow3 =

   1   3
   0   1

ans =

   10.483   14.152
   21.228   31.711

ans =

    2    4
    8   16



## Поэлементные операции с операнадами несовпадающих размеров (автосогласование размеров)
Возможность автоматически согласовывать размеры операндов очень удобна и часто используется на практике. Допустим, мы собираемся сложить две матрицы размера $3\times3$ и $3\times1$:

In [10]:
a = [1 2 3; 2 3 4; 3 4 5]
b = [100; 200; 300]
a_add_b = a + b

a =

   1   2   3
   2   3   4
   3   4   5

b =

   100
   200
   300

a_add_b =

   101   102   103
   202   203   204
   303   304   305



У матрицы `b` всего один столбец вместо трех, как у `a`. В этой ситуации столбец автоматически повторяется трижды перед сложением:

In [11]:
b_broadcasted = [b b b] # Это делается автоматически перед сложением
a_add_b = a + b_broadcasted # эквивалентно a + b

b_broadcasted =

   100   100   100
   200   200   200
   300   300   300

a_add_b =

   101   102   103
   202   203   204
   303   304   305



В следующем примере первый операнд повторяется так, чтобы получилась матрица размера $2\times3$

In [12]:
1 + [100 200 300; 400 500 600]
ones(2, 3) + [100 200 300; 400 500 600] # эквивалентно предыдущему

ans =

   101   201   301
   401   501   601

ans =

   101   201   301
   401   501   601



Т.е., если число добавляется к матрице, оно добавляется отдельно к каждому элементу.

Формально размеры операндов автоматически согласуются следующим образом. Если не совпадает количество строк у операндов, и у одного из них ровно одна строка, то эта строка повторяется столько раз, сколько строк во втором операнде. Аналогично согласуется количество столбцов.

В следующем примере расширяются оба операнда. В первом столбец повторяется трижды, во втором - строка.

In [13]:
a = [1; 2; 3]
b = [10 20 30]
a_add_b = a + b
a_expanded = [a a a]
b_expanded = [b ; b ; b]
a_add_b = a_expanded + b_expanded  # эквивалентно a + b

a =

   1
   2
   3

b =

   10   20   30

a_add_b =

   11   21   31
   12   22   32
   13   23   33

a_expanded =

   1   1   1
   2   2   2
   3   3   3

b_expanded =

   10   20   30
   10   20   30
   10   20   30

a_add_b =

   11   21   31
   12   22   32
   13   23   33



Другими словами, сумма столбца $a_i$ и строки $b_j$ это матрица $c_{i,j} = a_i + b_j$, где $i$ это индекс в строке, а $j$ это индекс в столбце.

До этого момента все примеры были про сложение. Вот примеры с другими операциями:

In [14]:
[1 2 3] - 1
[1 2; 3 4] .* 2
[1 2 3] .* [1; 2; 3]
1 ./ (1:10)
eye(3) ./ [1 10 100]

ans =

   0   1   2

ans =

   2   4
   6   8

ans =

   1   2   3
   2   4   6
   3   6   9

ans =

 Columns 1 through 8:

   1.00000   0.50000   0.33333   0.25000   0.20000   0.16667   0.14286   0.12500

 Columns 9 and 10:

   0.11111   0.10000

ans =

   1.00000   0.00000   0.00000
   0.00000   0.10000   0.00000
   0.00000   0.00000   0.01000



Операции умножения `*` и деления `/`, `\` матриц не согласуют автоматически размеры операндов, но есть важное исключение, если один из операндов число:

In [15]:
2 * ones(5) # умножь все элементы на 2 (the same as .*)
[1 2 3] / 3 # подели все элементы на 3 (the same as ./)

ans =

   2   2   2   2   2
   2   2   2   2   2
   2   2   2   2   2
   2   2   2   2   2
   2   2   2   2   2

ans =

   0.33333   0.66667   1.00000



## Другие операции
### Транспонирование
Транспонирование меняет местами строки и столбцы матрицы. Можно сказать, что отражает матрицу относительно главной диагонали. Обозначается символом апострофа после матрицы:

In [16]:
a = [1 2; 3 4; 5 6]
a'
b = 1:5
b'
(1:5)' # аналогично предыдущему, но без лишней переменной

a =

   1   2
   3   4
   5   6

ans =

   1   3   5
   2   4   6

b =

   1   2   3   4   5

ans =

   1
   2
   3
   4
   5

ans =

   1
   2
   3
   4
   5



### Обратная матрица и определитель
Вычисляются с помощью функций `inv` и `det`:

In [17]:
a = [1 2; 1 3]
a_inv = inv(a)
a * a_inv # the identity matrix eye(2)
det(a) # the determinant

a =

   1   2
   1   3

a_inv =

   3  -2
  -1   1

ans =

   1   0
   0   1

ans =  1


Есть еще много базовых алгебраических операций с матрицами: [https://octave.org/doc/v4.4.0/Basic-Matrix-Functions.html](https://octave.org/doc/v4.4.0/Basic-Matrix-Functions.html)

### Математические функции
Octave содержит много встроенных математических функций, таких как `sin`, `log`, `exp` (синус, логарифм, экспонента), они работают с каждым элементом по-отдельности:

In [18]:
x = [0 pi; 1 pi/2]
sin_x = sin(x)
exp(0:4)

x =

   0.00000   3.14159
   1.00000   1.57080

sin_x =

   0.00000   0.00000
   0.84147   1.00000

ans =

    1.0000    2.7183    7.3891   20.0855   54.5982



### Сумма, минимум, максимум of элементов матрицы
Следующие операции возвращают
* сумму элементов в каждом столбце матрицы
* минимальный элемент в каждом столбце матрицы
* максимальный элемент в каждом столбце матрицы

In [19]:
a = [1 6 8; 5 4 9; 2 7 3]
sum(a)
min(a)
max(a)

a =

   1   6   8
   5   4   9
   2   7   3

ans =

    8   17   20

ans =

   1   4   3

ans =

   5   7   9



Вспомните, что матрицы хранятся в памяти по колонкам, именно поэтому по-умолчанию эти функции работают с колонками.

**Но если матрица одномерная**, например, строка или столбец, эти функции работают на всех элементах матрицы:

In [20]:
sum([2 1 3]) # although, we have 3 columns, the function returns only one result
min([2 1 3])
max([2 1 3])

ans =  6
ans =  1
ans =  3


Как тогда получить сумму по строчкам? Один из ответов: можно использовать транспонирование. Как найти сумму всех элементов квадратной матрицы? Один из ответов: вызвать `sum` дважды.

Но оба результата можно получить и с помощью одного вызова функции `sum`. Попробуйте прочитать помощь по функции с помощью команды `help sum` и определить, как решить эти задачи, указав правильные аргументы при вызове `sum`.

Ответьте на аналогичные вопросы для функций `min` и `max`.

С помощью функций `min` и `max` можно узнать положения минимальных и максимальных элементов. Для этого нужно вызвать эти функции так, чтобы они вернули два результата. В Octave это делается с помощью специального синтаксиса с квадратными скобками:

In [21]:
a = [1 6 8; 5 4 9; 2 7 3]
[m, i] = min(a)

a =

   1   6   8
   5   4   9
   2   7   3

m =

   1   4   3

i =

   1   2   3



Функция `min` возвращает результат в две переменные: `m` это минимальные элементы, и `i` это индексы этих элементов в столбцах. Минимальный элемент в первом столбце находится по индексу 1, минимум во втором столбце находится по индексу 2, а минимум третьего столбца по индексу 3.