# Создание матриц

## Явное указание элементов

Используйте квадратные скобки, чтобы собрать матрицу из чисел или других матриц. Чтобы выстроить элементы в строчку, разделите их __пробелом__ или __запятой__, а чтобы выстроить в столбец, разделите их __переводом строки__ или __точкой с запятой__.

Все следующие примеры создают одну и ту же матрицу:

In [1]:
a = [1 2; 3 4]
b = [1, 2; 3, 4]
c = [1, 2
     3  4]

a =

   1   2
   3   4

b =

   1   2
   3   4

c =

   1   2
   3   4



Дальше примеры строчной и столбцовой матрицы:

In [2]:
a = [1 2 3 4 10 20]
b = [10; 20; 30]

a =

    1    2    3    4   10   20

b =

   10
   20
   30



Матрицы можно собирать из меньших матриц:

In [4]:
a = [1 2; 3 4]
b = [0 0]
c = [a; b] # разместить a над b
d = [a a; b b] # разместить a рядом с a, и на следующей строке b рядом с b
e = [a; 5 6] # добавить срточку под матрицей a

a =

   1   2
   3   4

b =

   0   0

c =

   1   2
   3   4
   0   0

d =

   1   2   1   2
   3   4   3   4
   0   0   0   0

e =

   1   2
   3   4
   5   6



## Оператор диапазона

Используйте оператор двоеточие, чтобы создать строчную матрицу, состоящую из последовательных чисел: 

In [5]:
a = 1:10 # числа от 1 до 10
b = 1:2:10 # числа от 1 до 10 с шагом 2
c = 10:-1:1 # числа от 10 вниз до 1
d = 1:0.1:2 # числа от 1 до 2 с шагом 0.1

a =

    1    2    3    4    5    6    7    8    9   10

b =

   1   3   5   7   9

c =

   10    9    8    7    6    5    4    3    2    1

d =

 Columns 1 through 8:

    1.0000    1.1000    1.2000    1.3000    1.4000    1.5000    1.6000    1.7000

 Columns 9 through 11:

    1.8000    1.9000    2.0000



## Функции создания матриц

Функция `linspace` похожа на оператор диапазона, но позволяет указать количество чисел в строке вместо шага:

In [6]:
a = linspace(1, 2, 21) # Создает матрицу-строку из равномерно распределенных
                       # чисел в диапазоне от 1 до 2 таким образом,
                       # чтобы получилось ровно 21 число.
b = 1:1/20:2 # Такой же результат, но с помощью оператора диапазона

a =

 Columns 1 through 8:

   1.0000   1.0500   1.1000   1.1500   1.2000   1.2500   1.3000   1.3500

 Columns 9 through 16:

   1.4000   1.4500   1.5000   1.5500   1.6000   1.6500   1.7000   1.7500

 Columns 17 through 21:

   1.8000   1.8500   1.9000   1.9500   2.0000

b =

 Columns 1 through 8:

    1.0000    1.0500    1.1000    1.1500    1.2000    1.2500    1.3000    1.3500

 Columns 9 through 16:

    1.4000    1.4500    1.5000    1.5500    1.6000    1.6500    1.7000    1.7500

 Columns 17 through 21:

    1.8000    1.8500    1.9000    1.9500    2.0000



In [8]:
a = zeros(2, 3) # матрица из нулей, размером 2x3
b = ones(3, 2) # матрица из единиц, размером 2x3
c = eye(4, 6) # матрица из нулей, но с единицами на главной диагонали
d = zeros(3) # Если в любую из приведенных функций подставить один аргумент,
             # получится квадратная матрица указанного размера

a =

   0   0   0
   0   0   0

b =

   1   1
   1   1
   1   1

c =

Diagonal Matrix

   1   0   0   0   0   0
   0   1   0   0   0   0
   0   0   1   0   0   0
   0   0   0   1   0   0

d =

   0   0   0
   0   0   0
   0   0   0

